name: PremiumLogin
author: NotReference
description: AutoLogin Premium Players Easily And Safely. Requires AuthMe, compatible with authmebungee.
main: it.notreference.bungee.premiumlogin.PremiumLoginMain
version: 1.3