# PremiumLogin 1.6.2 by NotReference
# AutoLogin Premium Players Easily. AuthMeBungee Support. Require AuthMe with BungeeCord Hook enabled to Work.

# - Utils -

# Select the authentication server.
auth-server: 'Auth'

# If you have problems with LuckPerms or other permission plugin problem, switch this to false.
setup-uuid: true

# Automatically send to lobby server after premium login?
send-to-lobby: false
lobby-server: 'Lobby'

# If you have AuthMe in all servers, change this true.
all-servers-are-server-auth: false

# Minecraft in the 1.6 implemented a new Authentication service. If you type this true, players with 1.5 ecc.. can login with premium too..
allow-premium-legacy-connections: false

# Log all actions to online staffs with permission premiumlogin.staff
log-staff: true

# /premiumlogin Informations.
disable-informations: false

# Permission for do /premium. Type nessuno for no permission.
premium-permission: 'nessuno'

# - Messages -

lock-login: '&aSuccessfully logged in with LockLogin API Support.'
join-with-premium: '&cUnable to connect. Your session is not vaild.'
auto-login-premium: '&aPremium account found. You are now logged in.'
error-generic: '&cAn error has occurred.'
unable: '&cUnable to login.'
default-login-system-switch-to-premiumlogin: '&aYour default login system has been switched to PremiumLogin.'
default-login-system-switch-to-authme: '&aYour default login system has been switched to AuthMe.'
enabled-autologin: '&aYou can now autologin with premium account.'
disable-autologin: '&aYou disabled autologin with premium account.'
no-premium: '&cYou are not premium.'
no-legacy: '&cUnable to join. Legacy is not allowed.'
not-used-premium-launcher: '&cFor enable this function, you need to be logged from the official &cMinecraft Premium Launcher.'
no-perms: '&cYou do not have permissions.'
staff-disable: '&cAn administrator disabled PremiumLogin for you. Please rejoin.'


# - Log Messages -
#[utente] for user name.
#[uuid] for uuid.
#[ip] for IP.

user-forcelogged: '&b[utente] &7has been forcelogged because is &aPremium&7.'
try-join-nopremium: '&b[utente] &7tried to join without the &eOfficial Minecraft Launcher&7.'
