# PremiumLogin 1.7 by NotReference
# Configuration file:
# - Utils -

# Notes: This config will be copied in a temp file. Do not delete it on plugin load or the plugin will not work.

# Select the authentication server.
auth-server: 'Auth'

# If you have problems with LuckPerms or other permission plugin problem, switch this to false.
setup-uuid: true

# Setup uuids only if that player activated /premium? This can help for fix permissions bugs or whitelist bugs.
# From (1.7) always true

# The method for setup uuids, example, parse to a premium uuid or parse to a sp uuid.
# SP or PREMUM.
# If you wanna to keep data use SP (LuckPerms can be bugged) or if you don't have LuckPerms you can switch this to SP.
setup-method: 'premium'

# Automatically send to lobby server after premium login?
send-to-lobby: false
lobby-server: 'Lobby'

# Do you wanna ignore errors and continue the plugin load without blocking?
ignore-update-errors: false

# Should we kick premium players with 2 sessions?
kick-on-2-sessions: true

# Ignore PlayerData errors and allow player to join without loaded data?
# Coming Soon.
# ignore-data-errors: false

# If you have AuthMe in all servers, change this true.
all-servers-are-server-auth: false

# Minecraft in the 1.6 implemented a new Authentication service. If you type this true, players with 1.5 ecc.. can login with premium too..
allow-premium-legacy-connections: false

# Log all actions to online staffs with permission premiumlogin.staff
log-staff: true

# /premiumlogin Informations.
disable-informations: false

# Permission for do /premium. Type nessuno for no permission.
premium-permission: 'nessuno'

# - Messages -

# Set automatically messages into the specifed language on plugin load?
# Supported Languages:
# it - Italiano
# es - Espanol
# en - English
# If you provide an invaild language, messages language will be replaced with following messages's language: (see #2)
# Auto Language is in BETA.
auto-language: false
language: 'it'

#2:

# NOTE:
# Read the codes.yml for more info about special chars like the spanish N and how place them in messages.

join-with-premium: '&cUnable to connect. Your session is not vaild.'
auto-login-premium: '&aPremium account found. You are now logged in.'
auto-register: '&aPremium account found. You have been automatically registered with password: {passw}'
change-auto-register: '&eChange now the password with /changepassword {passw} {passw}!'
error-generic: '&cAn error has occurred.'
2-sessions-kick: '&cUnable to join. You have already started a local session.'
unable: '&cUnable to login.'
unable-lobby: '&cUnable to send you to the lobby server.'
unable-data-init: '&cUnable to initialize the data handler for get your data. Please rejoin.'
default-login-system-switch-to-premiumlogin: '&aYour default login system has been switched to PremiumLogin.'
default-login-system-switch-to-authme: '&aYour disabled autologin.'
enabled-autologin: '&aYou can now autologin with premium account.'
disable-autologin: '&aYou disabled autologin with premium account.'
no-premium: '&cYou are not premium.'
no-legacy: '&cUnable to join. Legacy is not allowed.'
not-used-premium-launcher: '&cFor enable this function, you need to be logged from the official &cMinecraft Premium Launcher.'
no-perms: '&cYou do not have permissions.'
staff-disable: '&cAn administrator disabled PremiumLogin for you. Please rejoin.'
multiple-ips: '&cYou are already logged in as {user}. You cannot join with same IPs.'
minecraft-net-fail: '&cUnable to authenticate with Minecraft.net. Please retry.'
# data-error: '&cUnable to load your data. Please rejoin or contact a staffer.'
# data-broken: '&cUnable to load your data: Your data seems to be corrupted.'
# data-refresh: '&eYour data has been refreshed. Please rejoin.'

# - Log Messages -
#[utente] for user name.
#[uuid] for uuid.
#[ip] for IP.

user-forcelogged: '&b[utente] &7has been forcelogged because is &aPremium&7.'
try-join-nopremium: '&b[utente] &7tried to join without the &eOfficial Minecraft Launcher&7.'
