name: PremiumLogin
author: NotReference
description: AutoLogin Premium Players Easily And Safely. Requires AuthMe or LockLogin.
main: it.notreference.bungee.premiumlogin.PremiumLoginMain
version: 1.6.5